#!/usr/bin/env python3
"""
Signal Postmortem Recorder

Records post-trade outcomes for signals generated by edge pipeline and other skills.
Fetches realized returns (5-day, 20-day) and classifies outcomes.
"""

import argparse
import json
import os
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

# For FMP API calls
try:
    import requests

    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False


def get_fmp_api_key() -> Optional[str]:
    """Get FMP API key from environment or return None."""
    return os.environ.get("FMP_API_KEY")


def fetch_price_data(ticker: str, start_date: str, end_date: str, api_key: str) -> dict:
    """
    Fetch historical price data from FMP API (stable with v3 fallback).

    Returns dict mapping date string to close price.
    """
    if not HAS_REQUESTS:
        return {}

    endpoints = [
        ("https://financialmodelingprep.com/stable/historical-price-eod/full", True),
        ("https://financialmodelingprep.com/api/v3/historical-price-full", False),
    ]
    for base_url, is_stable in endpoints:
        try:
            if is_stable:
                url = base_url
                params = {"symbol": ticker, "from": start_date, "to": end_date, "apikey": api_key}
            else:
                url = f"{base_url}/{ticker}"
                params = {"from": start_date, "to": end_date, "apikey": api_key}
            resp = requests.get(url, params=params, timeout=30)
            if resp.status_code != 200:
                continue
            data = resp.json()
            historical = None
            # /stable/historical-price-eod/full antwortet mit einem blanken
            # Array. Ohne diesen Zweig faellt der Aufruf stillschweigend auf
            # den v3-Endpoint zurueck, der auf FMP Starter 403 liefert — und
            # ohne Kursdaten wird jede Rendite 0, also jedes Ergebnis NEUTRAL.
            if isinstance(data, list):
                historical = data
            elif isinstance(data, dict) and "historical" in data:
                historical = data["historical"]
            elif isinstance(data, dict) and "historicalStockList" in data:
                for entry in data["historicalStockList"]:
                    if entry.get("symbol", "").replace("-", ".") == ticker.replace("-", "."):
                        historical = entry.get("historical", [])
                        break
            if historical is not None:
                return {item["date"]: item["close"] for item in historical}
        except Exception:  # nosec B112 - intentional fallback to next FMP endpoint
            continue

    print(
        f"Warning: Failed to fetch price data for {ticker}: all endpoints failed", file=sys.stderr
    )
    return {}


def calculate_return(entry_price: float, exit_price: float) -> float:
    """Calculate percentage return."""
    if entry_price <= 0:
        return 0.0
    return (exit_price - entry_price) / entry_price


def classify_outcome(
    predicted_direction: str,
    return_pct: float,
    regime_at_signal: str,
    regime_at_exit: str,
    threshold: float = 0.005,
) -> str:
    """
    Classify signal outcome based on realized return and regime context.

    Returns one of: TRUE_POSITIVE, FALSE_POSITIVE, FALSE_POSITIVE_SEVERE,
                    REGIME_MISMATCH, NEUTRAL
    """
    # Check for regime mismatch
    if regime_at_signal != regime_at_exit and regime_at_exit != "UNKNOWN":
        if predicted_direction == "LONG" and return_pct < -0.02:
            return "REGIME_MISMATCH"
        if predicted_direction == "SHORT" and return_pct > 0.02:
            return "REGIME_MISMATCH"

    # Check for neutral (flat) outcome
    if abs(return_pct) < threshold:
        return "NEUTRAL"

    # Check direction match
    direction_match = (predicted_direction == "LONG" and return_pct > 0) or (
        predicted_direction == "SHORT" and return_pct < 0
    )

    if direction_match:
        return "TRUE_POSITIVE"

    # False positive - check severity
    if abs(return_pct) > 0.02:
        return "FALSE_POSITIVE_SEVERE"
    return "FALSE_POSITIVE"


def create_postmortem_record(
    signal: dict,
    realized_returns: dict,
    exit_price: float,
    exit_date: str,
    regime_at_exit: str = "UNKNOWN",
    outcome_notes: str = "",
) -> dict:
    """
    Create a postmortem record for a signal.
    """
    signal_id = signal.get("signal_id", "unknown")
    ticker = signal.get("ticker", "")
    signal_date = signal.get("signal_date", "")
    predicted_direction = signal.get("predicted_direction", "LONG")
    source_skill = signal.get("source_skill", "unknown")
    entry_price = signal.get("entry_price", 0.0)
    regime_at_signal = signal.get("regime", "UNKNOWN")

    # Use 5-day return for primary classification
    primary_return = realized_returns.get("5d", 0.0)

    outcome_category = classify_outcome(
        predicted_direction, primary_return, regime_at_signal, regime_at_exit
    )

    # Calculate holding days
    holding_days = 0
    if signal_date and exit_date:
        try:
            sig_dt = datetime.strptime(signal_date, "%Y-%m-%d")
            exit_dt = datetime.strptime(exit_date, "%Y-%m-%d")
            holding_days = (exit_dt - sig_dt).days
        except ValueError:
            pass

    return {
        "schema_version": "1.0",
        "postmortem_id": f"pm_{signal_id}",
        "signal_id": signal_id,
        "ticker": ticker,
        "signal_date": signal_date,
        "source_skill": source_skill,
        "predicted_direction": predicted_direction,
        "entry_price": entry_price,
        "realized_returns": realized_returns,
        "exit_price": exit_price,
        "exit_date": exit_date,
        "holding_days": holding_days,
        "outcome_category": outcome_category,
        "regime_at_signal": regime_at_signal,
        "regime_at_exit": regime_at_exit,
        "outcome_notes": outcome_notes,
        "recorded_at": datetime.utcnow().isoformat() + "Z",
    }


def process_signal(
    signal: dict,
    holding_periods: list,
    api_key: Optional[str] = None,
    manual_exit_price: Optional[float] = None,
    manual_exit_date: Optional[str] = None,
) -> Optional[dict]:
    """
    Process a single signal and create postmortem record.
    """
    ticker = signal.get("ticker", "")
    signal_date = signal.get("signal_date", "")
    entry_price = signal.get("entry_price", 0.0)

    if not ticker or not signal_date:
        print(f"Warning: Signal missing ticker or date: {signal}", file=sys.stderr)
        return None

    # Calculate date range for price fetching
    try:
        sig_dt = datetime.strptime(signal_date, "%Y-%m-%d")
    except ValueError:
        print(f"Warning: Invalid signal date: {signal_date}", file=sys.stderr)
        return None

    max_period = max(holding_periods)
    end_dt = sig_dt + timedelta(days=max_period + 5)  # Buffer for weekends

    # Fetch price data if API key available
    prices = {}
    if api_key:
        prices = fetch_price_data(ticker, signal_date, end_dt.strftime("%Y-%m-%d"), api_key)

    # Get entry price
    if entry_price <= 0:
        entry_price = prices.get(signal_date, 0.0)

    if entry_price <= 0:
        print(f"Warning: No entry price for {ticker} on {signal_date}", file=sys.stderr)
        return None

    # Calculate realized returns for each holding period
    realized_returns = {}
    exit_price = manual_exit_price
    exit_date = manual_exit_date

    for period in holding_periods:
        target_dt = sig_dt + timedelta(days=period)

        # Find closest trading day
        for offset in range(5):  # Check up to 5 days forward for weekends
            check_date = (target_dt + timedelta(days=offset)).strftime("%Y-%m-%d")
            if check_date in prices:
                period_price = prices[check_date]
                realized_returns[f"{period}d"] = calculate_return(entry_price, period_price)

                # Use first period's exit as default
                if exit_price is None:
                    exit_price = period_price
                    exit_date = check_date
                break

    # Use manual exit if provided
    if manual_exit_price is not None:
        exit_price = manual_exit_price
    if manual_exit_date is not None:
        exit_date = manual_exit_date

    if exit_price is None:
        exit_price = entry_price  # No change if no data
    if exit_date is None:
        exit_date = (sig_dt + timedelta(days=holding_periods[0])).strftime("%Y-%m-%d")

    return create_postmortem_record(signal, realized_returns, exit_price, exit_date)


def list_ready_signals(signals_dir: str, min_days: int = 5) -> list:
    """
    List signals that are ready for postmortem (past minimum holding period).
    """
    ready = []
    signals_path = Path(signals_dir)

    if not signals_path.exists():
        return ready

    cutoff_date = datetime.now() - timedelta(days=min_days)

    for json_file in signals_path.glob("*.json"):
        try:
            with open(json_file) as f:
                data = json.load(f)

            signals = data if isinstance(data, list) else data.get("signals", [])

            for signal in signals:
                signal_date = signal.get("signal_date", "")
                if signal_date:
                    sig_dt = datetime.strptime(signal_date, "%Y-%m-%d")
                    if sig_dt <= cutoff_date:
                        ready.append(signal)
        except (json.JSONDecodeError, KeyError) as e:
            print(f"Warning: Error reading {json_file}: {e}", file=sys.stderr)

    return ready


def main():
    parser = argparse.ArgumentParser(description="Record post-trade outcomes for signals")
    parser.add_argument("--signals-file", help="JSON file containing signals to process")
    parser.add_argument("--signals-dir", help="Directory containing signal JSON files")
    parser.add_argument("--signal-id", help="Specific signal ID for manual recording")
    parser.add_argument(
        "--holding-periods",
        default="5,20",
        help="Comma-separated holding periods in days (default: 5,20)",
    )
    parser.add_argument(
        "--exit-price", type=float, help="Manual exit price for single signal recording"
    )
    parser.add_argument(
        "--exit-date", help="Manual exit date (YYYY-MM-DD) for single signal recording"
    )
    parser.add_argument("--outcome-notes", default="", help="Notes about the outcome")
    parser.add_argument(
        "--list-ready", action="store_true", help="List signals ready for postmortem"
    )
    parser.add_argument(
        "--min-days", type=int, default=5, help="Minimum days for --list-ready (default: 5)"
    )
    parser.add_argument("--api-key", help="FMP API key (or set FMP_API_KEY env var)")
    parser.add_argument(
        "--output-dir",
        default="reports/",
        help="Output directory for postmortem records (default: reports/)",
    )

    args = parser.parse_args()

    # Get API key
    api_key = args.api_key or get_fmp_api_key()

    # Parse holding periods
    holding_periods = [int(p.strip()) for p in args.holding_periods.split(",")]

    # Create output directory
    output_dir = Path(args.output_dir)
    postmortems_dir = output_dir / "postmortems"
    postmortems_dir.mkdir(parents=True, exist_ok=True)

    # Handle --list-ready mode
    if args.list_ready:
        if not args.signals_dir:
            print("Error: --signals-dir required with --list-ready", file=sys.stderr)
            sys.exit(1)

        ready = list_ready_signals(args.signals_dir, args.min_days)
        print(f"Found {len(ready)} signals ready for postmortem:")
        for sig in ready:
            print(
                f"  {sig.get('signal_id', 'N/A')}: {sig.get('ticker', 'N/A')} on {sig.get('signal_date', 'N/A')}"
            )
        return

    # Handle single signal manual recording
    if args.signal_id:
        if not args.exit_price or not args.exit_date:
            print(
                "Error: --exit-price and --exit-date required for manual recording", file=sys.stderr
            )
            sys.exit(1)

        # Create minimal signal record
        signal = {
            "signal_id": args.signal_id,
            "ticker": args.signal_id.split("_")[1] if "_" in args.signal_id else "UNKNOWN",
            "signal_date": args.signal_id.split("_")[2]
            if args.signal_id.count("_") >= 2
            else datetime.now().strftime("%Y-%m-%d"),
            "predicted_direction": "LONG",
            "source_skill": "manual",
            "entry_price": 0.0,
        }

        postmortem = create_postmortem_record(
            signal, {}, args.exit_price, args.exit_date, outcome_notes=args.outcome_notes
        )

        # Save postmortem
        output_file = postmortems_dir / f"{postmortem['postmortem_id']}.json"
        with open(output_file, "w", encoding="utf-8") as f:
            json.dump(postmortem, f, indent=2)

        print(f"Saved postmortem: {output_file}")
        print(f"Outcome: {postmortem['outcome_category']}")
        return

    # Handle batch processing
    if not args.signals_file:
        print("Error: --signals-file required for batch processing", file=sys.stderr)
        sys.exit(1)

    signals_path = Path(args.signals_file)
    if not signals_path.exists():
        print(f"Error: Signals file not found: {args.signals_file}", file=sys.stderr)
        sys.exit(1)

    with open(signals_path) as f:
        data = json.load(f)

    signals = data if isinstance(data, list) else data.get("signals", [])

    if not signals:
        print("No signals found in input file", file=sys.stderr)
        sys.exit(1)

    if not api_key:
        print("Warning: No FMP API key available. Using manual entry prices only.", file=sys.stderr)

    # Process signals
    results = []
    for signal in signals:
        postmortem = process_signal(signal, holding_periods, api_key)
        if postmortem:
            results.append(postmortem)

            # Save individual postmortem
            output_file = postmortems_dir / f"{postmortem['postmortem_id']}.json"
            with open(output_file, "w", encoding="utf-8") as f:
                json.dump(postmortem, f, indent=2)

    # Save batch summary
    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    summary_file = output_dir / f"postmortem_batch_{timestamp}.json"
    summary = {
        "schema_version": "1.0",
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "source_file": str(signals_path),
        "total_signals": len(signals),
        "processed": len(results),
        "postmortems": results,
    }

    with open(summary_file, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    # Print summary
    outcomes = {}
    for pm in results:
        cat = pm["outcome_category"]
        outcomes[cat] = outcomes.get(cat, 0) + 1

    print(f"Processed {len(results)}/{len(signals)} signals")
    print("Outcome distribution:")
    for cat, count in sorted(outcomes.items()):
        print(f"  {cat}: {count}")
    print(f"Saved batch summary: {summary_file}")


if __name__ == "__main__":
    main()
